### ISSUE TITLE
MaterialListView can be even better

### ISSUE THREAD

**Issue by Stefan6440** [Taiizor/ReaLTaiizor#100]
### Bug explanation

Currently all header and content values are drawn left-aligned, even when setting textalign-right on the columns.
I think it would be great to have the headers and content drawn with the same alignment, as specified by the headers. 
It's is an detail, but an important one when the data contains numbers - and would add great value to the listview.
Look like the the the code is in methods OnDrawColumnHeader + OnDrawItem in MaterialListView.cs

I have just started looking into the Material component palette and it looks very promising. Great work!  I would like to contribute with some programming, so next time I will make an pull request.

### Version

Latest Greatest

**Comment by Stefan6440** [comment]
I just completed an pull request : Stefan6440-materiallistview-right-align-columns -  and will close this bug.

**Comment by Taiizor** [comment]
Thank you for your work. Can you test again after this PR to see if everything is fine?

**Comment by Stefan6440** [comment]
Hi, all good.  I have just verified all works as expected, and verified that the PR is merged all the way. Thanks for quick handling the PR, and again thanks for ReaLTaiizor, its great.  I will keep on working on my project, and might come up with some minor suggestions later on. Until then I am really enjoying using the Material controls.

![Verify-material-listview](https://github.com/Taiizor/ReaLTaiizor/assets/5719752/f7e7fa8d-7d0f-4235-b1f7-0695201bc5ce)
