### ISSUE TITLE
Treeview controls - Forever TreeView & Crown TreeView

### ISSUE THREAD

**Issue by ke-senthilkumar** [Taiizor/ReaLTaiizor#105]
### Bug explanation

I added nodes to the treeview controls but none of the nodes show up when run. The background is Black and I tried changing the background and foreground colors to different ones but in none of the schemes, the nodes show up.

[url=https://ibb.co/VBTW2Bp][img]https://i.ibb.co/Lp1znph/tvw.png[/img][/url]

Any suggestions?

### Version

3.7.9.0

**Comment by Taiizor** [comment]
CrownTreeView is working. Example usage for more information: https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Forms/Dialogs/DialogControls.cs

![CrownTreeView](https://github.com/Taiizor/ReaLTaiizor/assets/41683699/b589b9c6-c1df-4d0f-bbee-c7501e922454)
