### ISSUE TITLE
Material Button

### ISSUE THREAD

**Issue by aleffmoura** [Taiizor/ReaLTaiizor#121]
Is it possible to make the material button receive a font family? Or is there a limitation or something like that?

I saw that it is fixed in the code, there is no way to make it dynamic?

**Comment by Taiizor** [comment]
If im not mistaken, the Material theme uses the Roboto font family and this is not changed :/

https://github.com/Taiizor/ReaLTaiizor/issues/34#issuecomment-830093875

**Comment by aleffmoura** [comment]
If I wanted, could I modify it via code? then generate a PR for this change?

**Comment by aleffmoura** [comment]
modify it by code*

**Comment by aleffmoura** [comment]
If I want to contribute to the repository in this case, is it possible?

**Comment by Taiizor** [comment]
Yup, but this PR work should not have a negative impact on the Material theme components. Because this change will affect all Material theme components o_O

**Comment by aleffmoura** [comment]
ok, thanks
