### ISSUE TITLE
TabPage overlay causes error

### ISSUE THREAD

**Issue by m10613229** [Taiizor/ReaLTaiizor#122]
### Bug explanation

An error occurs as long as two TabPages are superimposed

![image](https://github.com/Taiizor/ReaLTaiizor/assets/63709419/e095b36f-0b65-41a3-a414-7d67d50d0091)
error message : stack trace :
![image](https://github.com/Taiizor/ReaLTaiizor/assets/63709419/cb01e6d6-fbac-4e36-8a57-0f74dcd1422c)

### Version

3.7.9.4

**Comment by Taiizor** [comment]
I fixed
![image](https://github.com/Taiizor/ReaLTaiizor/assets/41683699/0b148bac-c2da-4774-96d0-4b90f399b356)

**Comment by m10613229** [comment]
Thank you.
Could you release a new package?

**Comment by Taiizor** [comment]
Its possible (;

**Comment by Yanzhen-98** [comment]
The issue still exists in version 3.8.1.3.

**Comment by Taiizor** [comment]
@Yanzhen-98 I’ve just tested it and didn’t encounter any errors. You can verify it from the screenshot as well.

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <OutputType>WinExe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReaLTaiizor" Version="3.8.1.3" />
  </ItemGroup>

</Project>
```

<img width="1920" height="1032" alt="Image" src="https://github.com/user-attachments/assets/98497dda-f4d7-4a3a-b224-2b5bca1edde0" />
