### ISSUE TITLE
Controls.TagPage tab text paint

### ISSUE THREAD

**Issue by khdiy** [Taiizor/ReaLTaiizor#126]
### Bug explanation

Controls.TagPage tab text display different when it used with HopeTabPage. see picture below.
![image](https://github.com/Taiizor/ReaLTaiizor/assets/5748154/77c7b145-884a-4c1e-bfc2-787ae6b6a12a)
The text is not smooth.
Please have a look. Thanks.

### Version

3.7.9.5

**Comment by Taiizor** [comment]
I tested it and found that there is no problem.
![image](https://github.com/Taiizor/ReaLTaiizor/assets/41683699/a6448443-e2b6-4554-b549-cebc17097842)

**Comment by khdiy** [comment]
I think it's because your containner is not a System.Windows.Forms.Form. I didn't use the Form type from ReaLTaiizor. 
Please have another look. Thanks.

**Comment by Taiizor** [comment]
Yep, youre right (:
![image](https://github.com/Taiizor/ReaLTaiizor/assets/41683699/88591dce-f8cc-4567-b045-dd2b074581ba)

**Comment by Taiizor** [comment]
Problem is solved
![image](https://github.com/Taiizor/ReaLTaiizor/assets/41683699/5e2ac668-e454-4c64-b56f-408b7185f6e6)

**Comment by khdiy** [comment]
Good job, thanks.
