### ISSUE TITLE
ForeverForm not working at all

### ISSUE THREAD

**Issue by subjoel** [Taiizor/ReaLTaiizor#134]
### Bug explanation

when i try using the foreverform it gives an error on the line This.Load and it says Load is not declared. when i remove this line the designer isnt showed.

### Version

the latest

**Comment by Taiizor** [comment]
As seen in the video, it works smoothly.

https://github.com/Taiizor/ReaLTaiizor/assets/41683699/e36b2145-caf6-4812-a4e5-7296f3149645

**Comment by subjoel** [comment]
why is it for me not full screen? it shows a part white background.
![image](https://github.com/Taiizor/ReaLTaiizor/assets/89309881/68f8b944-db81-4562-9037-959edbfdcabf)
