### ISSUE TITLE
hopeDatePicker where is (ValueChange)?

### ISSUE THREAD

**Issue by khaled-shammari** [Taiizor/ReaLTaiizor#140]
### Bug explanation

hopeDatePicker where is (ValueChange)?

![datepicker](https://github.com/Taiizor/ReaLTaiizor/assets/149967654/215e7855-356a-4b38-a7a0-5e199cc7baa2)

### Version

3.7.9.6

**Comment by khaled-shammari** [comment]
I need select value and display it in label

**Comment by khaled-shammari** [comment]
I found the solution
like this
private void hopeDatePicker1_onDateChanged(DateTime newDateTime)
{
    label1.Text = hopeDatePicker1.Date.ToString();
}

**Comment by Taiizor** [comment]
> I found the solution like this private void hopeDatePicker1_onDateChanged(DateTime newDateTime) { label1.Text = hopeDatePicker1.Date.ToString(); }

I'm glad you found the solution.
