### ISSUE TITLE
compiled DLL more than 10M

### ISSUE THREAD

**Issue by FreeVB** [Taiizor/ReaLTaiizor#144]
### Bug explanation

The source code is about 8M, why is the size of the compiled DLL more than 10M? Is there a problem set up somewhere? Is there any way to make the compiled DLL smaller?

### Version

3.7.9.7

**Comment by Taiizor** [comment]
Actually, you have miscalculated. The total space occupied by the source codes is 9.91 MB. Therefore, reducing it doesn't seem quite feasible.
