### ISSUE TITLE
HopeCheckBox inside a parrotGroupBox inside of HopeTabPage glitches

### ISSUE THREAD

**Issue by avze** [Taiizor/ReaLTaiizor#148]
### Bug explanation

The Title basically explains it, I tried to make a form using the hopeform, then putting in the hope tab page, the inside of the tab page is the parroutgroupbox then its the hopecheckbox inside of the parroutgroupbox then it just wont save, no matter what i do and the application glitches out!

### Version

3.7.9.7

**Comment by Taiizor** [comment]
The issue will be resolved in the next version.

https://github.com/Taiizor/ReaLTaiizor/assets/41683699/382b85b8-f27a-4ab3-8c9f-0ee936a997e9
