### ISSUE TITLE
MaterialTabControl as DrawerMenu can not maximize from taskbar

### ISSUE THREAD

**Issue by IAMRAMKING** [Taiizor/ReaLTaiizor#150]
### Bug explanation

Could you please assist me with the issue I am experiencing when using the tabControl as DrawerTabControl in my WinForms application? Specifically, I am unable to maximize the application after minimizing it. However, I have observed that when the drawertabcontrol is not attached, the minimize and maximize functions work properly.
![image](https://github.com/Taiizor/ReaLTaiizor/assets/49708492/e7972d3a-347e-4680-845a-be0bca536252)

### Version

3.7.9.7

**Comment by IAMRAMKING** [comment]
@Taiizor I have observed that when the Application is "run as admin," then it cannot be maximized with MaterialTabControl as DrawerTabControl. Additionally, my application requires administrative privileges. 

To always open it as admin, I use the AppManifest file to set the Execution Level as "requireAdministrator" instead of "asInvoker."

![image](https://github.com/Taiizor/ReaLTaiizor/assets/49708492/85d61c58-87b4-4325-9409-572bd8ae1070)

**Comment by Taiizor** [comment]
Is there a problem as you mentioned in the example project below?

[ReaLTaiizor.UI](https://github.com/Taiizor/ReaLTaiizor/releases/download/v3.7.9.5/ReaLTaiizor.UI.7z)

**Comment by IAMRAMKING** [comment]
Yes, when running your example with administrative privileges, it is not maximizing.

**Comment by IAMRAMKING** [comment]
PFA The video as proof

https://github.com/Taiizor/ReaLTaiizor/assets/49708492/811349a0-a64d-45e3-b821-ac0dd1400847

**Comment by Taiizor** [comment]
Can you test this? [net48.zip](https://github.com/Taiizor/ReaLTaiizor/files/13888522/net48.zip)

**Comment by IAMRAMKING** [comment]
It is currently functioning. Thank you. 
Is it applicable to all versions of the dotNet Framework or only 4.8?

**Comment by Taiizor** [comment]
> It is currently functioning. Thank you. Is it applicable to all versions of the dotNet Framework or only 4.8?

It might be working on Windows 10, but unfortunately, it doesn't work on 11 :/

**Comment by IAMRAMKING** [comment]
I am using 4.8 and 4.8.1 on Windows 10.

**Comment by IAMRAMKING** [comment]
Will you publish it on nuget?

**Comment by Taiizor** [comment]
> I am using 4.8 and 4.8.1 on Windows 10.

I know.

> Will you publish it on nuget?

Not yet.

**Comment by Taiizor** [comment]
Again can you test this? [net48.zip](https://github.com/Taiizor/ReaLTaiizor/files/13888877/net48.zip)

**Comment by IAMRAMKING** [comment]
> Again can you test this? [net48.zip](https://github.com/Taiizor/ReaLTaiizor/files/13888877/net48.zip)

It's working fine as above example.

**Comment by Taiizor** [comment]
> > Again can you test this? [net48.zip](https://github.com/Taiizor/ReaLTaiizor/files/13888877/net48.zip)
> 
> It's working fine as above example.

Oh, that's great then! It works on Windows 11 too.

**Comment by Taiizor** [comment]
The new version is published. You can test it one last time and give feedback.

**Comment by IAMRAMKING** [comment]
> The new version is published. You can test it one last time and give feedback.

Hurray! My current application is working perfectly now. It is minimizing and maximizing correctly.

**Comment by Taiizor** [comment]
Furthermore, now you'll be able to customize the colors in the MaterialColorScheme class as you wish.

https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form17.cs#L32
https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form17.cs#L33
https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form17.cs#L34

**Comment by IAMRAMKING** [comment]
> Furthermore, now you'll be able to customize the colors in the MaterialColorScheme class as you wish.
> 
> https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form17.cs#L32 https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form17.cs#L33 https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form17.cs#L34

"Thank you, I have been using it for months already."

**Comment by Taiizor** [comment]
> > Furthermore, now you'll be able to customize the colors in the MaterialColorScheme class as you wish.
> > https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form17.cs#L32 https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form17.cs#L33 https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form17.cs#L34
> 
> "Thank you, I have been using it for months already."

Yes, it has been around for a long time, but it has never been this customizable before (:
