### ISSUE TITLE
ValueChanged event for ForeverNumeric

### ISSUE THREAD

**Issue by YuLiangLin** [Taiizor/ReaLTaiizor#156]
ForeverNumeric is inherented from Control, could you add ValueChanged event for that?

**Comment by Taiizor** [comment]
In the next version of ReaLTaiizor, the ValueChanged event will be active.

**Comment by YuLiangLin** [comment]
> In the next version of ReaLTaiizor, the ValueChanged event will be active.

Great! thanks for your help
