### ISSUE TITLE
CyberTextBox Not Change ForeColor

### ISSUE THREAD

**Issue by Veroyman** [Taiizor/ReaLTaiizor#157]
### Bug explanation

When i set the forecolor property, it stay on 245, 245, 245 or Color.WhiteSmoke.

### Version

3.8.0.1 and 3.8.0

**Comment by Taiizor** [comment]
CyberTextBox, CyberRichTextBox, and CyberColorPicker now support the ForeColor property. It will be active in the next version of ReaLTaiizor.
