### ISSUE TITLE
Documentation is required to use!

### ISSUE THREAD

**Issue by MIMAXUZ** [Taiizor/ReaLTaiizor#16]
I have been using **ReaLTaiizor** for the last two weeks. But there is a lot of uncertainty in the use of some features and elements. It would be very easy to understand if it was documentation. 
**At least the following**
- How to use the elements,
- installation and use of companions
- installation and use of themes
and etc...

**So far I have had the following problems**
- I was able to use only LoftForm and Material Forms (I had problems using the rest),
- When I use FlowLayoutPanel (in dock fill mode) BorderStyle is closed and not visible (only worked on LostForm). Also has some problems.
- AutoSize in Panels, Buttons, and TextBoxes is sometimes very large.

These are becoming incomprehensible, and it would be great if any example demo program with all the elements used was documented or put in place. 
At the very least, the demo programs listed in **Overview ** would be easier to understand even if the sources were uploaded.
Thanks...

**Comment by Taiizor** [comment]
> At the very least, the demo programs listed in **Overview ** would be easier to understand even if the sources were uploaded.
Thanks...
https://github.com/Taiizor/ReaLTaiizor/tree/develop/demo/ReaLTaiizor.UI There are a total of 21 Forms in the project at the address. There are examples you want.
And More https://github.com/Taiizor/ReaLTaiizor/tree/develop/sample

**Comment by Taiizor** [comment]
> These are becoming incomprehensible, and it would be great if any example demo program with all the elements used was documented or put in place.
https://github.com/Taiizor/ReaLTaiizor/tree/develop/demo/ReaLTaiizor.UX I'm going to do everything I can to make sure that the project at address is ready soon.

**Comment by MIMAXUZ** [comment]
> > These are becoming incomprehensible, and it would be great if any example demo program with all the elements used was documented or put in place.
> > https://github.com/Taiizor/ReaLTaiizor/tree/develop/demo/ReaLTaiizor.UX I'm going to do everything I can to make sure that the project at address is ready soon.

@Taiizor Taiizor Thanks for response. Very good library to use. It will be great for a programmer if you have instructions and documentation ... It helps me a lot in new projects.
