### ISSUE TITLE
The button component background color cannot be modified

### ISSUE THREAD

**Issue by not-shut** [Taiizor/ReaLTaiizor#160]
### Bug explanation

I set the background color of the component to be red, but the color of this button component still does not change, may I ask whether it is a bug or I did not fix the setting somewhere?
![1](https://github.com/Taiizor/ReaLTaiizor/assets/101622293/e2f13701-8ce6-48ba-ba9b-95011a5555a6)
![2](https://github.com/Taiizor/ReaLTaiizor/assets/101622293/203cab23-f2fa-44f6-a76a-4095813fbb2d)

### Version

3.8.0.2

**Comment by Taiizor** [comment]
Everything looks fine for FoxButton. You can already see it in the images below.

![ReaLTaiizor-Fox-Button](https://github.com/Taiizor/ReaLTaiizor/assets/41683699/4e8e0416-c9df-4db6-8180-c90646943fcc)
![ReaLTaiizor-Fox-Button](https://github.com/Taiizor/ReaLTaiizor/assets/41683699/8b3ef00f-878f-4ea3-b415-29a72e46bb3d)

**Comment by Taiizor** [comment]
Everything looks fine for Button. You can already see it in the images below.

![ReaLTaiizor-Button](https://github.com/Taiizor/ReaLTaiizor/assets/41683699/d1f876c2-54b3-464c-a896-8b4bf4cb4c1f)
![ReaLTaiizor-Button](https://github.com/Taiizor/ReaLTaiizor/assets/41683699/76a41a31-9c45-445a-9a2b-d03ed4afd55a)
