### ISSUE TITLE
ParrotForm (ReaLTaiizor.Forms) bugs

### ISSUE THREAD

**Issue by 1JayPeng** [Taiizor/ReaLTaiizor#168]
### Bug explanation

when  i get ParrotForm (ReaLTaiizor.Forms) in my program,there is a bug.
the version is 3.8.0.5
here is the bug
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=ReaLTaiizor
  StackTrace:
   在 ReaLTaiizor.Forms.ParrotForm.RefreshUI() 在 /_/src/ReaLTaiizor/Forms/Panel/ParrotForm.cs 中: 第 299 行

```
here is the code
```
 /// <summary>
 /// Required method for Designer support - do not modify
 /// the contents of this method with the code editor.
 /// </summary>
 private void InitializeComponent()
 {
     parrotForm1 = new ReaLTaiizor.Forms.ParrotForm();
     SuspendLayout();
```

### Version

3.8.0.5

**Comment by Taiizor** [comment]
The ParrotForm works via drag-and-drop method into a Form window. If you are trying to use it as shown in the image below, you might be doing it wrong.

![ReaLTaiizor-Parrot-Form](https://github.com/user-attachments/assets/62ca00e3-c6e4-4678-81bd-16ec8cde845f)

The mentioned [line 299](https://github.com/Taiizor/ReaLTaiizor/blob/9989abb8e8360207a374728ffc99a891651d124a/src/ReaLTaiizor/Forms/Panel/ParrotForm.cs#L299C13-L299C35) is related to setting the Dock property of ParrotForm to Fill. If you manually changed the Dock property of ParrotForm, you are likely to encounter the error.

**Comment by Taiizor** [comment]
I understand the issue now. The error will be resolved in the next released version.
