### ISSUE TITLE
Unable to programmatically set button color

### ISSUE THREAD

**Issue by clippyb** [Taiizor/ReaLTaiizor#172]
### Bug explanation

Setting the PressedColor value of a button has no effect, not a massive problem if the button exists in the designer to change it in properties but dynamically changing this within my program does not work
![Screenshot 2024-08-27 073236](https://github.com/user-attachments/assets/19d6d3f8-359b-40fc-a2e2-13f37f9383e7)

### Version

3.8.0.6

**Comment by clippyb** [comment]
I was able to fix the issue by modifying the class 

public Color PressedColor
        {
            get => _PressedColor;
            set
            {
                _PressedColor = value;
                Invalidate();
            }
        }

Inserting the following below _PressedColor
PressedGB = new LinearGradientBrush(new Rectangle(0, 0, Width, Height), PressedColor, PressedColor, 90.0F);

**Comment by Taiizor** [comment]
This issue will be resolved in the next update for the Button component.
