### ISSUE TITLE
Form17 window shakes when DrawerAutoShow=true

### ISSUE THREAD

**Issue by toolgood** [Taiizor/ReaLTaiizor#180]
### Bug explanation

![动画3](https://github.com/user-attachments/assets/1b23ff58-9366-4bd9-9f65-7ddc40fc6b88)

### Version

Form17

**Comment by toolgood** [comment]
Adding the following code seems to have solved the problem

MaterialForm.cs
``` cs
            _drawerShowHideAnimManager = new AnimationManager
            {
                AnimationType = AnimationType.EaseInOut,
                Increment = 0.04,
                Singular=false, //add codes
            };
```

**Comment by Taiizor** [comment]
I tested this and I dont seem to have any problems.
