### ISSUE TITLE
[MaterialForm]:Why is there a deviation between input and display？ 

### ISSUE THREAD

**Issue by txt101766** [Taiizor/ReaLTaiizor#186]
### Bug explanation

![image](https://github.com/user-attachments/assets/5a6641ac-70f3-463a-bc1a-31de260451c5)

### Version

3.8.0.7

**Comment by Taiizor** [comment]
The Material theme uses the Roboto font family, and as far as I remember, you cannot change it. Even if the Roboto font family is not installed on your computer, it should still display correctly. Honestly, I’m not sure what might be causing this issue.

**Comment by txt101766** [comment]
> The Material theme uses the Roboto font family, and as far as I remember, you cannot change it. Even if the Roboto font family is not installed on your computer, it should still display correctly. Honestly, I’m not sure what might be causing this issue.

Thank you for your reply!
I deleted the local Roboto font family and the problem was resolved.
