### ISSUE TITLE
multiselect property in MaterialListBox is not work.

### ISSUE THREAD

**Issue by ahnjs1987** [Taiizor/ReaLTaiizor#191]
### Bug explanation

multiselect property in MaterialListBox is not work.
I want to select 1 or more items in ListBox,  So I set true on multiselect property in MaterialListBox control.
After that, I was running app for check multiselect feature, but I can only select one item.

Is there any configuration to enable this feature?

### Version

3.8.0.9

**Comment by Taiizor** [comment]
This issue will be resolved in the next update. The **MultiSelect** property needs to be set to `true`, and you must hold down the **CTRL** or **Shift** key while selecting objects. 

https://github.com/user-attachments/assets/1bb09d7f-71b3-418f-97a0-3d416c461080

To access the selected items, you can use the following example: 

```csharp
foreach (object item in materialListBox1.SelectedItems)
{
    MessageBox.Show((item as MaterialListBoxItem).Text);
}
```
