### ISSUE TITLE
ReaLTaiizor.Controls.Checkbox Checked property updated via code wont fire CheckChanged event

### ISSUE THREAD

**Issue by diegocamarotta** [Taiizor/ReaLTaiizor#20]
I am using some checkboxes from the ReaLTaiizor.Controls.Checkbox control on a C# Winforms project and changing the Checked property value from code (during Form Load event)  does not trigger the CheckChanged event (which works fine while ticking the checkbox in the UI). I validated that this doesnt even work while changing the value from a manually clicked button either and that a  regular Winform Checkbox does indeed make it work

1  -  Add a ReaLTaiizor.Controls.Checkbox set to Checked = false in a form
2 -   Add a message box or whatever code to the checkbox's CheckedChanged event
3 -   Set it to Checked = true in the Form's Load event
4 -   Execute

Expected
The code from the CheckChanged event is executed

Actual
The checkbox checked state is changed but the code does not execute

**Comment by Taiizor** [comment]
Fixed List:
- AirCheckBox
- AloneCheckBox
- FoxCheckBox
- MoonCheckBox
- RibbonCheckBox
- FoxCheckBoxEdit
- SkyCheckBox
- CheckBox
- SpaceCheckBox

[Commit](https://github.com/Taiizor/ReaLTaiizor/commit/da76d074a03049aca8e9ba291b6f19e47ca98a2a)
