### ISSUE TITLE
How to change the font and can't keypress CJK language in some textbox elements

### ISSUE THREAD

**Issue by Seed0728** [Taiizor/ReaLTaiizor#25]
How to change the font in Material Theme ?
For example changing the font size, font family, etc in the properties but nothing happened
and the MaterialTextBox is pretty cool but can't keypress CJK language for use

 - OS: windows 10 1909
 - .netFramework: 461

**Comment by Taiizor** [comment]
In some themes, the Font is unfortunately not changed.
The components of the Material Theme consist of the Roboto font family.
