### ISSUE TITLE
List of bugs/unfunctional things

### ISSUE THREAD

**Issue by HideakiAtsuyo** [Taiizor/ReaLTaiizor#27]
=> Direct
==> Indirect
===========
- Material Button issue:
==============================
- Material Label issue:

**Comment by HideakiAtsuyo** [comment]
Tell me when all of them are fixed :)

**Comment by Taiizor** [comment]
> Tell me when all of them are fixed :)

You can be sure of that ;)

**Comment by HideakiAtsuyo** [comment]
Fixed?

**Comment by HideakiAtsuyo** [comment]
At this moment i just need a function to hide/show tabs in Material :)

Btw it's laggy when i make a login thing

**Comment by HideakiAtsuyo** [comment]
Don't just react lmao i need you ! 
And i promise if you fix them i will make 10 commits per months 💯

**Comment by Taiizor** [comment]
> Don't just react lmao i need you !
> And i promise if you fix them i will make 10 commits per months 💯

What component is this?

![image](https://user-images.githubusercontent.com/41683699/110986278-86771080-837e-11eb-9cc8-01784c14b76d.png)

**Comment by HideakiAtsuyo** [comment]
> > Don't just react lmao i need you !
> > And i promise if you fix them i will make 10 commits per months 💯
> 
> What component is this?
> 
> ![image](https://user-images.githubusercontent.com/41683699/110986278-86771080-837e-11eb-9cc8-01784c14b76d.png)

I was half sleeping at the moment of those screenshots so, SelectTab is from `System.Windows.Forms.TabControl` but it's working lol

**Comment by HideakiAtsuyo** [comment]
The `.Hide()` is from `System.Windows.Forms.Controls` but it's not working with `ReaLTaiizor` so if you can make one that can work with it :)

**Comment by Taiizor** [comment]
If the project files containing these errors are still there, can you send them?

**Comment by HideakiAtsuyo** [comment]
> If the project files containing these errors are still there, can you send them?

You want me to download the project from the last commit and test the bugs that i added in the first message?

**Comment by Taiizor** [comment]
> > If the project files containing these errors are still there, can you send them?
> 
> You want me to download the project from the last commit and test the bugs that i added in the first message?

No, do you still have the project that contains the mistakes you reported to me?

**Comment by HideakiAtsuyo** [comment]
> > > If the project files containing these errors are still there, can you send them?
> > 
> > 
> > You want me to download the project from the last commit and test the bugs that i added in the first message?
> 
> No, do you still have the project that contains the mistakes you reported to me?

Yes

**Comment by Taiizor** [comment]
> > > > If the project files containing these errors are still there, can you send them?
> > > 
> > > 
> > > You want me to download the project from the last commit and test the bugs that i added in the first message?
> > 
> > 
> > No, do you still have the project that contains the mistakes you reported to me?
> 
> Yes

Can you send me the project?

**Comment by HideakiAtsuyo** [comment]
> > > > > If the project files containing these errors are still there, can you send them?
> > > > 
> > > > 
> > > > You want me to download the project from the last commit and test the bugs that i added in the first message?
> > > 
> > > 
> > > No, do you still have the project that contains the mistakes you reported to me?
> > 
> > 
> > Yes
> 
> Can you send me the project?

Yes wait

**Comment by HideakiAtsuyo** [comment]
https://privnote.com/tfaOgtFf#UIb4mRoHE

**Comment by Taiizor** [comment]
Drawer Issue Fixed

![Drawer](https://user-images.githubusercontent.com/41683699/111009479-c5b85800-83a4-11eb-949c-5b0e3815ee8f.gif)

**Comment by HideakiAtsuyo** [comment]
> Drawer Issue Fixed
> 
> ![Drawer](https://user-images.githubusercontent.com/41683699/111009479-c5b85800-83a4-11eb-949c-5b0e3815ee8f.gif)

Nice and for hide tabs(A tabs container(for hide all tabs directly) and a precise tab) you have an idea?

**Comment by Taiizor** [comment]
`DrawerHideTabName = new string[] { Home.Name };` It hides tab elements. But no showing :)
`DrawerHideTabName = Array.Empty<string>();` This line of code doesn't work.

![Hide](https://user-images.githubusercontent.com/41683699/111023267-15207780-83e9-11eb-8ef6-dc9458a85590.gif)

**Comment by HideakiAtsuyo** [comment]
It's good lmao it's working perfectly, but mainly i was asking about Login and Register things(LoginRegister tabs name) to hide them to use another tabs(but it's prolly the same way) :)

**Comment by Taiizor** [comment]
You can turn off mouse interaction instead of hiding it :)

`DrawerNonClickTabPage = new TabPage[] { LOGIN };`
`DrawerNonClickTabPage = Array.Empty<TabPage>();`

![NonClick](https://user-images.githubusercontent.com/41683699/111025897-3c327580-83f8-11eb-9b7d-9a145652fee8.gif)

**Comment by Taiizor** [comment]
Button shadow fixed

![ButtonShadow](https://user-images.githubusercontent.com/41683699/111028216-5a9f6d80-8406-11eb-8796-b47ba68f5dcc.gif)

**Comment by HideakiAtsuyo** [comment]
> You can turn off mouse interaction instead of hiding it :)
> 
> `DrawerNonClickTabPage = new TabPage[] { LOGIN };`
> `DrawerNonClickTabPage = Array.Empty<TabPage>();`
> 
> ![NonClick](https://user-images.githubusercontent.com/41683699/111025897-3c327580-83f8-11eb-9b7d-9a145652fee8.gif)

Yes, but it doesn't look very professional + i was speaking about https://i.imgur.com/k4FchBb.png but it's basically the same thing than the used thing for the settings/home lol

**Comment by Taiizor** [comment]
MaterialButton, MaterialCard, MaterialCheckListBox, MaterialFloatingActionButton, MaterialLabel, MaterialCheckBox, MaterialComboBox, MaterialRadioButton, MaterialSingleTextBox, MaterialTextBox, MaterialSwitch black background fixed

![MultiComp](https://user-images.githubusercontent.com/41683699/111029933-8f182700-8410-11eb-879c-4f2d9c498129.gif)

**Comment by HideakiAtsuyo** [comment]
> MaterialButton, MaterialCard, MaterialCheckListBox, MaterialFloatingActionButton, MaterialLabel, MaterialCheckBox, MaterialComboBox, MaterialRadioButton, MaterialSingleTextBox, MaterialTextBox, MaterialSwitch black background fixed
> 
> ![MultiComp](https://user-images.githubusercontent.com/41683699/111029933-8f182700-8410-11eb-879c-4f2d9c498129.gif)

Like a boss 😎

**Comment by HideakiAtsuyo** [comment]
Btw i'm curious, i got a laggy result(the form) with an if statement with a button, have you the same issue?

**Comment by Taiizor** [comment]
`materialTabSelector1.SelectorHideTabName = new string[] { tabPage2.Name }` It hides tab elements.
`materialTabSelector1.SelectorHideTabName = Array.Empty<string>();` This line of code doesn't work.

![Selector](https://user-images.githubusercontent.com/41683699/111031086-ddc8bf80-8416-11eb-8118-071d6997fa2a.gif)

`materialTabSelector1.SelectorNonClickTabPage = new TabPage[] { tabPage3 }`
`materialTabSelector1.SelectorNonClickTabPage = Array.Empty<TabPage>();`

**Comment by Taiizor** [comment]
> Btw i'm curious, i got a laggy result(the form) with an if statement with a button, have you the same issue?

[Mouse->MessageFilter: true => false]
![image](https://user-images.githubusercontent.com/41683699/111031362-42384e80-8418-11eb-9cc5-0af80b3c3808.png)
![image](https://user-images.githubusercontent.com/41683699/111031383-66942b00-8418-11eb-9a82-9b0731930b1f.png)

**Comment by HideakiAtsuyo** [comment]
Taiizor is a boss

**Comment by HideakiAtsuyo** [comment]
Btw can you fix:

`materialTabSelector1.SelectorHideTabName = Array.Empty<string>(); ` "This line of code doesn't work."
`DrawerHideTabName = Array.Empty<string>();` "This line of code doesn't work."

Or you want me to make a PR in the day for them?
