### ISSUE TITLE
.NET5 Poison/Material tab pages navigation not working

### ISSUE THREAD

**Issue by roos-robert** [Taiizor/ReaLTaiizor#30]
**To Reproduce**
Adding a tab control and a collection of tabs, when in the live editor trying to navigate between tabs to design their content it's not working. Working as expected in .NET 4.6/4.8.

**Expected behavior**
To be able to navigate between tabs in the live editor

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 (latest build)
Visual Studio 16.8.x/16.9.x

**Comment by Taiizor** [comment]
![image](https://user-images.githubusercontent.com/41683699/109297527-2ee78980-7843-11eb-8642-7d1974d119d0.png)

As shown in the picture above, MaterialTabControl works correctly. If you want to use MaterialTabControl, MaterialTabSelector should also be used.

![image](https://user-images.githubusercontent.com/41683699/109297863-ba611a80-7843-11eb-9ad0-bba1be152555.png)

**Comment by roos-robert** [comment]
> If you want to use MaterialTabControl, MaterialTabSelector should also be used.

Feeling stupid, I missed this! Thanks for getting back to me so quickly, issue resolved. 😃

**Comment by Taiizor** [comment]
![image](https://user-images.githubusercontent.com/41683699/109302142-f4351f80-7849-11eb-8d15-4fd6ac6e1bfd.png)
![image](https://user-images.githubusercontent.com/41683699/109302162-fc8d5a80-7849-11eb-8808-1c16e36e82db.png)

Not only PosionTabControl, but MetroTabControl was also faulty, but both were corrected. That won't be a problem in the next release.
