### ISSUE TITLE
Suite of #27

### ISSUE THREAD

**Issue by HideakiAtsuyo** [Taiizor/ReaLTaiizor#31]
Btw can you fix:

`materialTabSelector1.SelectorHideTabName = Array.Empty<string>(); ` "This line of code doesn't work."
`DrawerHideTabName = Array.Empty<string>();` "This line of code doesn't work."

Or you want me to make a PR in ~ 1-2 day(s) for them?

**Comment by Taiizor** [comment]
I tried so hard, but I couldn't find a solution.

**Comment by HideakiAtsuyo** [comment]
I will see later

**Comment by HideakiAtsuyo** [comment]
Btw drag & drop is broken with ReaLTaiizor 😂

**Comment by Taiizor** [comment]
> Btw drag & drop is broken with ReaLTaiizor 😂

Drag & drop of what?

**Comment by HideakiAtsuyo** [comment]
> > Btw drag & drop is broken with ReaLTaiizor 😂
> 
> Drag & drop of what?

File on text box for set the textboxt text to the file path :)

**Comment by Taiizor** [comment]
> > > Btw drag & drop is broken with ReaLTaiizor 😂
> > 
> > 
> > Drag & drop of what?
> 
> File on text box for set the textboxt text to the file path :)

I did not understand. Can you show it with a GIF?

**Comment by HideakiAtsuyo** [comment]
> > > > Btw drag & drop is broken with ReaLTaiizor 😂
> > > 
> > > 
> > > Drag & drop of what?
> > 
> > 
> > File on text box for set the textboxt text to the file path :)
> 
> I did not understand. Can you show it with a GIF?

I can't before Yesterday, i'm not at home so no computer lol..
