### ISSUE TITLE
希望支持本地化一下（Local）

### ISSUE THREAD

**Issue by ping9719** [Taiizor/ReaLTaiizor#33]
感谢作者的辛苦更新。（Thanks to the author for the long update）
我的英文不好，我会采用双语的方式。（My English is poor, so I can speak two languages.）

PoisonMessageBoxControl.xml

`<?xml version="1.0" encoding="utf-8" ?>
<root>
  <Localization>
    <Key>Ok</Key>
    <Value>&amp;确定</Value>
  </Localization>
  <Localization>
    <Key>Cancel</Key>
    <Value>&amp;取消</Value>
  </Localization>
  <Localization>
    <Key>Retry</Key>
    <Value>&amp;重试</Value>
  </Localization>
  <Localization>
    <Key>Yes</Key>
    <Value>&amp;是</Value>
  </Localization>
  <Localization>
    <Key>No</Key>
    <Value>&amp;否</Value>
  </Localization>
  <Localization>
    <Key>Abort</Key>
    <Value>&amp;终止</Value>
  </Localization>
  <Localization>
    <Key>Ignore</Key>
    <Value>&amp;忽略</Value>
  </Localization>
</root>`

PoisonToggle.xml

`<?xml version="1.0" encoding="utf-8" ?>
<root>
  <Localization>
    <Key>StatusOn</Key>
    <Value>开</Value>
  </Localization>
  <Localization>
    <Key>StatusOff</Key>
    <Value>关</Value>
  </Localization>
</root>`

控件“MaterialTextBox”的右键菜单为英文，我并没有找到本地化的方式。（The right click menu of the control "MaterialTextBox" is in English, I did not find a way to localize it.）

`            switch (toolStripItemClickedEventArgs.ClickedItem.Text)
            {
                case "Cut":
                    Cut();
                    break;
                case "Copy":
                    Copy();
                    break;
                case "Paste":
                    Paste();
                    break;
                case "Delete":
                    SelectedText = string.Empty;
                    break;
                case "Select All":
                    SelectAll();
                    break;
            }`

**Comment by Taiizor** [comment]
`CultureInfo cultureInfo = new("zh");
Application.CurrentCulture = cultureInfo;`
![image](https://user-images.githubusercontent.com/41683699/114177986-c2819f00-9945-11eb-8d7c-9f935724802a.png)

**Comment by ping9719** [comment]
非常感谢（thank）
希望更新到包版本（v3.7.8.4）中。（want to update to the version of the package (3.7.8.4).）
如果我想修改代码的一些问题，我应该怎么办？（I want to fix a bug in the code,what should I do?）
是这样子提交问题吗？还是...？（Submit the lssues as do now,Or....?）

**Comment by Taiizor** [comment]
> 非常感谢（thank）
> 希望更新到包版本（v3.7.8.4）中。（want to update to the version of the package (3.7.8.4).）
> 如果我想修改代码的一些问题，我应该怎么办？（I want to fix a bug in the code,what should I do?）
> 是这样子提交问题吗？还是...？（Submit the lssues as do now,Or....?）

I'll release version 3.7.8.4 soon.
You can do PR work or let me know here.
I didn't translate the Material theme because it doesn't support multiple languages because it requires radical change.

**Comment by ping9719** [comment]
明白了（get it）
我看到了很久，现在才回复（I have seen it for a long time and only reply now）
我觉得3.7.8.4的版本从net framework 4.61开始是一个错误的选择（Version 3.7.8.4 starting with NET Framework 4.61 was an incorrect choice）
3.7.8.3最低兼容性都是net framework 4.0（3.7.8.3 Minimum compatibility is NET Framework 4.0）
如果实在要抛弃建议从net framework 4.5开始（There is really no way.I suggest you start at net framework 4.5）

**Comment by Taiizor** [comment]
> 明白了（get it）
> 我看到了很久，现在才回复（I have seen it for a long time and only reply now）
> 我觉得3.7.8.4的版本从net framework 4.61开始是一个错误的选择（Version 3.7.8.4 starting with NET Framework 4.61 was an incorrect choice）
> 3.7.8.3最低兼容性都是net framework 4.0（3.7.8.3 Minimum compatibility is NET Framework 4.0）
> 如果实在要抛弃建议从net framework 4.5开始（There is really no way.I suggest you start at net framework 4.5）

.NET Core compatibility requires a Minimum .NET Framework 4.6.1.

**Comment by ping9719** [comment]
我觉得不是你说的这样（I don't think so）
我查看了ReaLTaiizor.csproj 文件（I opened the ReaLTaiizor.csproj file）
文件中的 PropertyGroup >> TargetFrameworks （property PropertyGroup >> TargetFrameworks ）
你的标记为：（This is what you wrote）
`<TargetFrameworks>net461;net462;net47;net471;net472;net48;netcoreapp3.0-windows;netcoreapp3.1-windows;net5.0-windows;net6.0-windows</TargetFrameworks>`

其实我觉得没有必要，你可以这样子写：（I don't think it's necessary，could write it like）
`<TargetFrameworks>net45;netcoreapp3.0;net5.0-windows</TargetFrameworks>`

然后编辑会出现错误，我们只需要这样子改动代码，就可以支持net45：（And then you get an error in the build，Follow the instructions to modify the code，can now support 4.5）

`Array.Empty<string>();`
替换为（replace..）
`new List<string>().ToArray();`

如果支持 net40 就不要使用 System.Windows.Forms.HasDropDown 就行了（Don't use System.Windows.Forms.HasDropDown if  support NET40）

![image](https://user-images.githubusercontent.com/9651046/115825065-7d786500-a43b-11eb-80e5-f4959d25f615.png)

**Comment by Taiizor** [comment]
> 我觉得不是你说的这样（I don't think so）
> 我查看了ReaLTaiizor.csproj 文件（I opened the ReaLTaiizor.csproj file）
> 文件中的 PropertyGroup >> TargetFrameworks （property PropertyGroup >> TargetFrameworks ）
> 你的标记为：（This is what you wrote）
> `<TargetFrameworks>net461;net462;net47;net471;net472;net48;netcoreapp3.0-windows;netcoreapp3.1-windows;net5.0-windows;net6.0-windows</TargetFrameworks>`
> 
> 其实我觉得没有必要，你可以这样子写：（I don't think it's necessary，could write it like）
> `<TargetFrameworks>net45;netcoreapp3.0;net5.0-windows</TargetFrameworks>`
> 
> 然后编辑会出现错误，我们只需要这样子改动代码，就可以支持net45：（And then you get an error in the build，Follow the instructions to modify the code，can now support 4.5）
> 
> `Array.Empty<string>();`
> 替换为（replace..）
> `new List<string>().ToArray();`
> 
> 如果支持 net40 就不要使用 System.Windows.Forms.HasDropDown 就行了（Don't use System.Windows.Forms.HasDropDown if support NET40）
> 
> ![image](https://user-images.githubusercontent.com/9651046/115825065-7d786500-a43b-11eb-80e5-f4959d25f615.png)

Now I remember why I was removing their supports.
[ReaLTaiizor Actions](https://github.com/Taiizor/ReaLTaiizor/actions)

![image](https://user-images.githubusercontent.com/41683699/115866529-730d9980-a442-11eb-9781-1ea184a91d5f.png)
![image](https://user-images.githubusercontent.com/41683699/115866401-49ed0900-a442-11eb-93b9-ab895c353f6d.png)
