### ISSUE TITLE
cannot change the font size of the button

### ISSUE THREAD

**Issue by avlobn** [Taiizor/ReaLTaiizor#34]
Hello, thank you very much for this library, although I still have one problem, I cannot change the font size of the buttons, even changing it in the properties nothing happens, I found that your button has only 3 types, but how can I change font size?

**Comment by Taiizor** [comment]
> Hello, thank you very much for this library, although I still have one problem, I cannot change the font size of the buttons, even changing it in the properties nothing happens, I found that your button has only 3 types, but how can I change font size?

What button are you talking about?

**Comment by avlobn** [comment]
> > Hello, thank you very much for this library, although I still have one problem, I cannot change the font size of the buttons, even changing it in the properties nothing happens, I found that your button has only 3 types, but how can I change font size?
> 
> What button are you talking about?

material

**Comment by Taiizor** [comment]
> > > Hello, thank you very much for this library, although I still have one problem, I cannot change the font size of the buttons, even changing it in the properties nothing happens, I found that your button has only 3 types, but how can I change font size?
> > 
> > 
> > What button are you talking about?
> 
> material

In some themes, the Font is unfortunately not changed.
The components of the Material Theme consist of the Roboto font family.
