### ISSUE TITLE
Setting custom ColorStyle for poisonStyleManager

### ISSUE THREAD

**Issue by debug-duck** [Taiizor/ReaLTaiizor#36]
Thank you for a great control library!

I have a question: how to define a color for (ColorStyle)15 in poisonStyleManager?

**Comment by Taiizor** [comment]
[Add Color](https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/Colors/Poison.cs#L11)

[Add Color Style](https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/Enum/Poison/ColorStyle.cs#L5)

[Add Color Pen](https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/Extension/Poison/PoisonPens.cs#L29)

[Add Color Brush](https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/Extension/Poison/PoisonBrushes.cs#L29)

[Add Style Color](https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/Drawing/Poison/PoisonPaint.cs#L839)
[Add Style Brush](https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/Drawing/Poison/PoisonPaint.cs#L861)
[Add Style Pen](https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/Drawing/Poison/PoisonPaint.cs#L883)

I hope there's nowhere I've forgotten

**Comment by cldhsej** [comment]
Hello is there a demo for Add Color Style Custom?
