### ISSUE TITLE
Crown controls color bug

### ISSUE THREAD

**Issue by ghost** [Taiizor/ReaLTaiizor#37]
Idk if i am missing something...but i am unable to change the color of crown controls...they are only of dark theme/ dark color.

Edit : I just found Theme interface in source...just need to use it....i will try and update again.
Edit : Idk man, unable to figure out how to use theme, unable to find methods or property to set it...need help.

Also, when I delete controls (tried with tab controls for now), visual studio stop working...the window itself is working/responding, but the cursor gets stuck at the loading type and nothing is clickable.

**Comment by Taiizor** [comment]
Theme Provider for Crown Theme does not work comprehensively.

[For Dark Theme](https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form21.cs#L205)
[For Light Theme](https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form21.cs#L233)

[You can remove any remaining question marks from this Demo project.](https://github.com/Taiizor/ReaLTaiizor/tree/develop/demo/ReaLTaiizor.UI)

**Comment by ghost** [comment]
I see...thanks a lot, I understand now :).
