### ISSUE TITLE
Material Demo code

### ISSUE THREAD

**Issue by masterchen** [Taiizor/ReaLTaiizor#46]
Very good project ! Thank  you !
I like the design of "material demo" gif shows  , i found when i launch project "ReaLTaiizor.UI", i can see the form.   but the form icon show it is a file , not a window form,  when i  right click the mouse on the form file (such as form17 ) there is no selection  "open  in the form designer"  , thank you ~

**Comment by Taiizor** [comment]
i understand what you are trying to say. as you can see below, i have no problem.
probably related to your .NET or Visual Studio version.
in addition, compiling the project can fix this problem.
![image](https://user-images.githubusercontent.com/41683699/151174763-81e04246-b4bc-4a68-9983-97c5db3e1979.png)

**Comment by Taiizor** [comment]
> i understand what you are trying to say. as you can see below, i have no problem. probably related to your .NET or Visual Studio version. ![image](https://user-images.githubusercontent.com/41683699/151174763-81e04246-b4bc-4a68-9983-97c5db3e1979.png)

in addition, compiling the project can fix this problem.

**Comment by masterchen** [comment]
@Taiizor  Thanks for your reminder.
I changed the "ReaLTaiizor.UI.csproj.user" file , after adding the  code below , then i can open Form17.cs in the desginer:
`	<Compile Update="Form17.cs">
      <SubType>Form</SubType>
    </Compile>`
