### ISSUE TITLE
Cannot hide child controls on a Metro tab page.

### ISSUE THREAD

**Issue by rrirower** [Taiizor/ReaLTaiizor#47]
**Describe the bug**
A child control (eg. combobox or label) on a Metro tab page cannot be hidden using ".Visbile = false" or ".Hide()".

**To Reproduce**
1. Create a child control on a Metro tab page.
2. In the Load event, try hiding it.
3. Control will not hide and remains visible.

**Expected behavior**
The control should be hidden when requested.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Taiizor** [comment]
I tested and saw the problem.
After the TabPage is opened, you can hide the child control.
I'll have to do test operations on the library to fully solve it. It may take some time..

[BugTest.zip](https://github.com/Taiizor/ReaLTaiizor/files/8053920/BugTest.zip)

**Comment by Taiizor** [comment]
After the new version is released, it gets fixed after setting ControlsVisible to false.
But im not sure when the new version will be released.

![image](https://user-images.githubusercontent.com/41683699/153719316-dc4d4a36-e181-48cb-9195-47aec6d3c8c3.png)

**Comment by rrirower** [comment]
Thank you for the quick response.

**Comment by rrirower** [comment]
This bug has been marked as solved.  Has it made it into a release?  I'm still having problems with this bug using version 3.7.8.8.  The only way I can "hide" a visible control on a MetroTabPage is to remove it like this:

`metroTabPageSearch.Controls.Remove(_control_);`

**Comment by Taiizor** [comment]
Version 3.7.8.8 was used in the attached project. The ControlsVisible value of the MetroTabControl component is marked as false. There is no problem when the visibility value of any component on the MetroTabControl is set to false.

Attachment:
[BugTest.zip](https://github.com/Taiizor/ReaLTaiizor/files/9955731/BugTest.zip)

Video:
https://user-images.githubusercontent.com/41683699/200423859-3a365c9a-3d6e-47b3-9ea4-d6dc695251b2.mp4

**Comment by rrirower** [comment]
Thanks again.  I was unaware that I had to set the value of 'ControlsVisible' to false in order to allow the individual controls the ability to set their 'Visible' property to false.  It now works.

**Comment by Taiizor** [comment]
nP (:
I wish you good work.
