### ISSUE TITLE
How can i build support .net core

### ISSUE THREAD

**Issue by yangliGit** [Taiizor/ReaLTaiizor#49]
like this:
![image](https://user-images.githubusercontent.com/13326497/160214978-9e5a9dfa-c458-4508-b3bc-31c930b2eb8e.png)

This is the result of my packing:
![image](https://user-images.githubusercontent.com/13326497/160215301-e77119e1-350e-4c6a-88f9-082920887a84.png)

**Comment by Taiizor** [comment]
By activating the following line
https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/ReaLTaiizor.csproj#L8

Then change the following line to comment line
https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/ReaLTaiizor.csproj#L4

For Example
`<!--<TargetFramework>net48</TargetFramework>-->`
`<!--<TargetFramework>net5.0-windows</TargetFramework>-->`
`<!--<TargetFrameworks>net48;net5.0-windows;net6.0-windows</TargetFrameworks>-->`
`<!--<TargetFrameworks>net48;net5.0-windows;net6.0-windows;net7.0-windows</TargetFrameworks>-->`
`<TargetFrameworks>net48;netcoreapp3.1-windows;net5.0-windows;net6.0-windows;net7.0-windows</TargetFrameworks>`

**Comment by yangliGit** [comment]
Thank you very much
