### ISSUE TITLE
Draw focus rectangle 

### ISSUE THREAD

**Issue by arthuridea** [Taiizor/ReaLTaiizor#50]
**Is your feature request related to a problem? Please describe.**
I think it will be better if adding a dotted rectangle when the control is in active state.

**Describe the solution you'd like**
1. Add a `_focusState` field.
2. Change `_focusState` in `GotFocus` and `LostFocus` event handler.
3. In OnPaint event handler,invoking `ControlPaint.DrawFocusRectangle` method to draw a rectangle.We can use `Style` (dark or light) property to determine the forecolor and backcolor of focusing rectangle.

**Describe alternatives you've considered**

**Additional context**

**Comment by Taiizor** [comment]
There are many button components. If you wish, you can do PR work on any buttons you want.
Because i see you know something about it.

**Comment by arthuridea** [comment]
> There are many button components. If you wish, you can do PR work on any buttons you want. Because i see you know something about it.

thanks for replying.
I finnally decided to override the component in my code as  it is only a small tool in my work and not be fully tested.I tried to find a more elegant way but it seems behaving differently for each component.  I majorly focus on web development while coding in desktop for less than a week :(
