### ISSUE TITLE
MetroTabControl ForegroundColor property to public

### ISSUE THREAD

**Issue by mbmigone** [Taiizor/ReaLTaiizor#53]
Any chance to change the ForegroundColor property from private to public so the tabs and the line under them can be customized?

Currently, it is:
https://github.com/Taiizor/ReaLTaiizor/blob/c603f6e63c935254c1cd8555d42d79acb945957d/src/ReaLTaiizor/Controls/TabControl/MetroTabControl.cs#L295-L296

which only allows to use the default color `Color.FromArgb(65, 177, 225)` defined in the ApplyTheme method, and the option is not available in the properties.

![imagen](https://user-images.githubusercontent.com/25875176/164383549-bbaa95a2-14ce-41cb-bd32-275990f96834.png)
![imagen](https://user-images.githubusercontent.com/25875176/164383985-9befb0c7-e453-4108-8b1b-7ad3c269094f.png)

I tried myself in a clone of the project and it worked properly, but I'm not sure if it will interfere with something else.

![imagen](https://user-images.githubusercontent.com/25875176/164384483-2ae4ead7-bde0-48d8-93a7-00cedfa4938f.png)
![imagen](https://user-images.githubusercontent.com/25875176/164384638-8e2673d8-fcd5-44f6-97fa-97db5d58bc3b.png)
![imagen](https://user-images.githubusercontent.com/25875176/164384668-fcb6dd82-a918-4ab3-aaa2-077d4394a1d3.png)

**Comment by Taiizor** [comment]
You can customize Metro components the way you want using StyleManager.
Customizable sample theme file is below.

https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/Resources/Metro/Metro%20Theme.xml

How to use this theme file is shown in the example below.

https://github.com/Taiizor/ReaLTaiizor/blob/e34f1fd59bdc5c3380b52708c6b61d2d1cd127f1/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form19.cs#L55

Or you can do it by typing the path to the theme file.
`metroStyleManager1.CustomTheme = @"C:\Custom Theme.xml";`

**Comment by mbmigone** [comment]
Thanks so much for the reply. I wasn't aware of that. Still, wouldn't it be handy to have it as an option to edit that property from the properties panel and even change it in runtime through accessing it as `metroTabControl.ForegroundColor = some Color` instead of having to choose from different .xml files. ?
I don't know really, is just a question/suggestion. But anyways, thanks again for the response.
