### ISSUE TITLE
System.PlatformNotSupportedException: 'Operation is not supported on this platform.' when calling PoissonMessageBox.Show

### ISSUE THREAD

**Issue by rrirower** [Taiizor/ReaLTaiizor#55]
**Describe the bug**
I wrote method A in dll1 that calls method B in dll2.  Method B calls PoissonMessageBox.Show() directly.

**To Reproduce**
1. Call PoissonMessageBox.Show from a dll.

**Expected behavior**
I would expect the message box to display.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
method B code follows:

        public static void ReportError(LogType _action, string _title, string _message, Form _parent, 
            MessageBoxButtons _buttons, MessageBoxIcon _icon, object[] _arguments=null)
        {
            int index = 0;

            if (_arguments != null)
            {
                foreach (string arg in _arguments)
                {
                    _arguments[index++] = arg.Replace("\r\n", string.Empty);
                }
            }

            _message = WriteLog(_action, _message, _arguments);

            PoisonMessageBox.Show(_parent, _message, _title, _buttons, _icon);
        }

If I substitute a standard MessageBox.Show("error") call, the code does not throw and error.

**Comment by Taiizor** [comment]
This bug has been resolved with commit. This behavior will not be in the next new release.

**Comment by rrirower** [comment]
Will the fix make it into a future release?

**Comment by Taiizor** [comment]
Of course (;
