### ISSUE TITLE
TabControl is crashing everytime

### ISSUE THREAD

**Issue by Steven-L-42** [Taiizor/ReaLTaiizor#57]
Your TabControl with the Name 'TabControl' looks very pretty, but i cant use them.

it still crashes after pressing Start.

**Comment by Taiizor** [comment]
![image](https://user-images.githubusercontent.com/41683699/172021348-f3235461-62d6-4b3b-b549-bf611f7abe71.png)


If you tell me which component it is, I might be able to help.

**Comment by Steven-L-42** [comment]
sure. i mean TabPage, i thought his name is also TabControl, but its TabPage
Here 2 images..
Before Compile:
![before](https://user-images.githubusercontent.com/102829233/172027519-0958cef3-874f-4d49-8e50-d149d14b1d32.png)

After Compile:
![after](https://user-images.githubusercontent.com/102829233/172027522-23dc07fb-9491-418c-be77-474f3e7014ed.png)

**Comment by Taiizor** [comment]
it works fine in my tests
![image](https://user-images.githubusercontent.com/41683699/178012002-de79f550-248c-4ab7-b3be-3aa3fde792b5.png)
![image](https://user-images.githubusercontent.com/41683699/178012699-e108bfbc-04b0-41eb-856b-86bdfdbaf525.png)
![image](https://user-images.githubusercontent.com/41683699/178015413-d7a53cf5-56cf-4228-833c-d2ef7515deb4.png)
