### ISSUE TITLE
HopeNumeric

### ISSUE THREAD

**Issue by IAmOrion** [Taiizor/ReaLTaiizor#63]
**Describe the bug**
HopeNumeric allows for a number to be typed in.  At least, it's possible to click the number and use a keyboard to type a number.
HOWEVER - this number doesn't remain, it gets replaced by the last known number unless I specifically press Enter on my keyboard (Which then makes the window "not allowed" ding as if to imply you can't do that

**To Reproduce**
- Add HopeNumeric control
- Click the field and enter a number
- Click/navigate off the control
- Number reverts back to last known number either set by the +/- or set in the ValueNumber property field

**Expected behavior**
it should simply accept and remain on the number manually typed it.  There's no point in having the field allow keyboard input if it won't keep the number typed in

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Vivaldi
- Visual Studio 2022
- C# .NET Windows Forms Application

EDIT
** Other Info **
I realise from looking at the source of the HopeNumeric that it is coded that pressing enter (keycode 13) does 'accept' the number etc but ideally this should happen automatically like the default NumericUpDown control does (and some other custom numeric controls out there)

**Comment by Taiizor** [comment]
If the Enter key is a requirement, the EnterKey value must be marked as true. As long as this value is false, whatever is written in the box will be valid.
