### ISSUE TITLE
Add Project solution of overview

### ISSUE THREAD

**Issue by rubenbb85** [Taiizor/ReaLTaiizor#64]
Is it possible to add the solution projects, which, are shown in the "overview" section? Specially the Material and Metro.

Thanks in advance.

**Comment by Taiizor** [comment]
Everything you have seen in the project is available in this repository.

All:
https://github.com/Taiizor/ReaLTaiizor/tree/develop/demo
https://github.com/Taiizor/ReaLTaiizor/tree/develop/ready
https://github.com/Taiizor/ReaLTaiizor/tree/develop/sample

Material: https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form17.cs
Metro: https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Form19.cs

You can access the overview projects of other designs by changing the part of the line that says `Form17()` in the link below.
https://github.com/Taiizor/ReaLTaiizor/blob/develop/demo/ReaLTaiizor.UI/ReaLTaiizor.UI/Program.cs#L25

**Comment by rubenbb85** [comment]
Great, thanks for the info.
