### ISSUE TITLE
Whole Controls Inside ParrotForm Goes Disappear

### ISSUE THREAD

**Issue by squiey** [Taiizor/ReaLTaiizor#66]
I've added some controls into **Parrot Form** and close the design window **after saved all changes**. 

![Screenshot_118](https://user-images.githubusercontent.com/106429978/178983205-630418ca-1b72-437d-8645-74cccef17063.png)

When I open the design window again I see whole controls inside Parrot Form has been disappeared.

![Screenshot_119](https://user-images.githubusercontent.com/106429978/178983893-c84f8a1f-90a2-4c70-84a8-3cd68635b57f.png)

Checked the controls on property window and they all are there! I did try those controls to bring to front but it didn't work.

![Screenshot_120](https://user-images.githubusercontent.com/106429978/178983907-b138eccb-ee9f-4639-8a37-2959ad06137c.png)

**Comment by Taiizor** [comment]
ParrotForm has WorkingArea. Check that the components you added are in WorkingArea.

![image](https://user-images.githubusercontent.com/41683699/178986419-8c1b2bbc-8ea0-4843-b0e0-34a1187a13b2.png)

**Comment by squiey** [comment]
> ParrotForm has WorkingArea. Check that the components you added are in WorkingArea.

I am sure to I've drag and dropped controls from toolbox onto WorkingArea. Should I do any other process?

**Comment by Taiizor** [comment]
> > ParrotForm has WorkingArea. Check that the components you added are in WorkingArea.
> 
> I am sure to I've drag and dropped controls from toolbox onto WorkingArea. Should I do any other process?

nope

**Comment by squiey** [comment]
> > > ParrotForm has WorkingArea. Check that the components you added are in WorkingArea.
> > 
> > 
> > I am sure to I've drag and dropped controls from toolbox onto WorkingArea. Should I do any other process?
> 
> nope

Ok, this is a bug in this case. I hope it will be fixed as soon as possible.

**Comment by squiey** [comment]
Visual Studio throw this error when I try to move label with arrow keys on the keyboard

![Screenshot_121](https://user-images.githubusercontent.com/106429978/178992887-2c9c4119-5647-4ecd-9fe8-5cfb81d630e2.png)
