### ISSUE TITLE
Can't change the color of a button

### ISSUE THREAD

**Issue by PurelyAndy** [Taiizor/ReaLTaiizor#68]
**Describe the bug**
I see no way to change the color of a button.

**To Reproduce**
1. Go to 'your design'
2. Click on 'the toolbox'
3. Scroll down to 'button'
4. Make button
5. Can't change the color?

**Expected behavior**
I should have an option to change the color.

**Screenshots**
no

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser not applicable
 - Version 3.7.8.7

**Comment by Taiizor** [comment]
which button?

**Comment by PurelyAndy** [comment]
> which button?

The default button, it might affect other buttons too. I'm not currently sure, because I've broken my project.
Edited, I've fixed my project to the point where I can see your options in the toolbox, and I believe that it affects all buttons.

**Comment by Taiizor** [comment]
There are button customizations in the picture below. You probably didn't see it.

![image](https://user-images.githubusercontent.com/41683699/181944437-4c1b9888-fb0f-4bcd-8d1b-0737d977b59f.png)

**Comment by codingbrush** [comment]
To change the color of a button the Inactive Color Property has to be changed to the preferred color.
