### ISSUE TITLE
Assembly 'ReaLTaiizor' uses 'System.Windows.Forms, Version=6.0.2.0' which has a higher version than referenced assembly 'Version 6.0.0.0'

### ISSUE THREAD

**Issue by PurelyAndy** [Taiizor/ReaLTaiizor#69]
**Describe the bug**
It's using a newer version of winforms, and I have no clue how to upgrade to it.

**To Reproduce**
No idea. Other people seem to use it fine, I just made a new Windows Forms app with .NET 6.0.

**Expected behavior**
Not this compile error, for sure.

**Desktop (please complete the following information):**
Windows 10
10

**Additional context**

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1705	Assembly 'ReaLTaiizor' with identity 'ReaLTaiizor, Version=3.7.8.7, Culture=neutral, PublicKeyToken=null' uses 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' which has a higher version than referenced assembly 'System.Windows.Forms' with identity 'System.Windows.Forms, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	TestRealTaiizor	C:\Users\me\source\repos\TestRealTaiizor\CSC	1	Active
`

**Comment by Taiizor** [comment]
Versions are available at the address below. If you use the latest version, it's fine.

https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by PurelyAndy** [comment]
Thought I had the latest version of .NET. Apparently, I was wrong.
