### ISSUE TITLE
[Question] Where can i get source sample of Crown Theme

### ISSUE THREAD

**Issue by lehoai** [Taiizor/ReaLTaiizor#70]
The Crown Theme that shows on this gif 
https://raw.githubusercontent.com/Taiizor/ReaLTaiizor/develop/.screenshots/Crown.gif
 is very match to my app.
Can u send me the source code of this sample or a link to download it?

Thank u so much!

**Comment by Taiizor** [comment]
The source codes of all the projects in the pictures you see here are in this repository.

You can download the compiled version of the project from the links below.

https://github.com/Taiizor/ReaLTaiizor/releases/download/v3.7.8.7/ReaLTaiizor.UI.zip
https://github.com/Taiizor/ReaLTaiizor/releases/download/v3.7.8.7/ReaLTaiizor.UI.7z

You must write 'Crown' in the application's launch argument.

![image](https://user-images.githubusercontent.com/41683699/182145947-8e37a274-0e2a-4f73-88d9-2fac9bc2096b.png)

Source codes are available at the link below. The 'Form21' parts of the project contain the 'Crown' theme.

https://github.com/Taiizor/ReaLTaiizor/tree/develop/demo/ReaLTaiizor.UI

**Comment by lehoai** [comment]
@Taiizor 
Thank you for your reply.
I am using this library to build an enterprise application (mean it's not free, I will sell it to my customer), then do i have to publicize my source code? Sorry, i have no idea about GPL license ( i read a lot but cant understand)

**Comment by Taiizor** [comment]
When you look at the license link below, there are titles in the form of a summary at the top. You can get general information.

![image](https://user-images.githubusercontent.com/41683699/182850035-7a2cf2ee-8f10-4487-8d8f-4e1215c99d24.png)
https://github.com/Taiizor/ReaLTaiizor/blob/develop/LICENSE

No need to share your source code.

**Comment by lehoai** [comment]
@Taiizor 
Thank u so much!!

**Comment by Taiizor** [comment]
nP

**Comment by lehoai** [comment]
@Taiizor 
I asked the lawyer, even if you allowed me to use this library to build an enterprise application, it's not allowed to keep source code private.
The only way is change license to MIT.

**Comment by Taiizor** [comment]
The next version will be released under the MIT license.

**Comment by lehoai** [comment]
@Taiizor 
Thank you so much!
I am waiting for it.
