### ISSUE TITLE
MetroTabControl no longer supports more than one tab page.

### ISSUE THREAD

**Issue by rrirower** [Taiizor/ReaLTaiizor#71]
### Bug explanation

Prior to version 3.7.8.7, I was able to edit tab pages on a MetroTabControl.  After 3.7.8.7, I am no longer able to edit all pages of the tab control.  For example, I have a MetroTabControl that contains two pages.  I can click on the title of the first page but not the second.  Clicking on the second page puts me into the code.

This bug can be reproduced with the following steps:

- Drag a new MetroTabControl from the designer.
- Add the first tab page.
- Now, try to add a second tab page.
- An error message is thrown and the second page is disabled.

The error looks like this:
![Metro tab Capture](https://user-images.githubusercontent.com/34550407/183683874-8b45ff17-b207-4d99-ad39-58101bdde86b.PNG)

I am using Visual Studio 2022 version 17.2.6

### Version

3.7.8.7

**Comment by Taiizor** [comment]
What is your .NET Framework or .NET & .NET Core version?

**Comment by rrirower** [comment]
.Net 5.0

**Comment by Taiizor** [comment]
It will work fine again in the next version.

**Comment by rrirower** [comment]
Thank you for the quick response to this bug.
