### ISSUE TITLE
 ReaLTaiizor.pdb not loaded

### ISSUE THREAD

**Issue by veeravadhanimn** [Taiizor/ReaLTaiizor#79]
### Bug explanation

I am facing this problem when a MaterialComboBox (filled with data dynamically) is clicked, it is showing this error:

System.NullReferenceException: 'Object reference not set to an instance of an object.' 

### Version

3.07.8.0

**Comment by Taiizor** [comment]
What is your .NET version?

Can you write your way of adding data in the combobox?

```materialComboBox1.Items.Add("Data1");```

```materialComboBox1.Items.AddRange(new object[] {```
```	"Data2",```
```	"Data3",```
```	"Data4"}```
```);```

I didn't get any errors in .NET 6, 3.7.8.7 version.
