### ISSUE TITLE
MetroNumeric - Increment/decrement is random

### ISSUE THREAD

**Issue by ke-senthilkumar** [Taiizor/ReaLTaiizor#83]
### Bug explanation

Hi

Thanks for the controls and I am trying to use in a personal capacity. 

I am using a numeric control. I can set the Min and Max values but the Increment value is not present. When I try + or -, the increment is like 5,6,7 etc. Not a steady increment.  Is there a way I can achieve increments of 1 or other numbers?

### Version

3.7.8.8

**Comment by Taiizor** [comment]
The increment value is now supported. If the increase is more than expected, increase the HoldInterval value.

**Comment by Taiizor** [comment]
> The increment value is now supported. If the increase is more than expected, increase the HoldInterval value.

The changes will take effect in the next release.
