### ISSUE TITLE
Can't drag style manager to form

### ISSUE THREAD

**Issue by rrirower** [Taiizor/ReaLTaiizor#89]
### Bug explanation

The MetroStyleManager appears in my Visual Studio toolbox.  I assumed I could drag it to a form and style the form or other components.  When I attempted to do this I got:

![Capture](https://user-images.githubusercontent.com/34550407/209187655-d258a274-7997-4589-8f55-b99d313e86f0.PNG)

Is this correct?  
How do I style components?  Via dragging to a form, or, programmatically?

### Version

3.7.8.8

**Comment by Taiizor** [comment]
When you drag and drop the MetroStyleManager to the form, the error should not occur.
But if the error occurs, copy the following file to `C:\Users\{USERNAME}\AppData\Roaming\Microsoft\Windows\Templates` folder.

https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/Resources/Metro/Metro%20Theme.xml
![image](https://user-images.githubusercontent.com/41683699/209205911-a9bb6c7a-3c09-4ce8-b479-1d92df1d484c.png)
![Theme](https://user-images.githubusercontent.com/41683699/209207586-21a17042-897b-4a44-b3a4-5cb6b611814c.gif)

**Comment by rrirower** [comment]
The AppData folder already contained a copy of ThemeFile.xml.  I renamed it and copied the contents of the file you provided into  Visual Studio Code and saved it with 'ThemeFile.xml' as the name in the AppData folder.  I then tried to drag the MetroStyleManager component to a form.  I now receive a different message:

![Capture](https://user-images.githubusercontent.com/34550407/209213171-4d1fe0a6-9eea-4f0e-833e-37232a948c63.PNG)

**Comment by Taiizor** [comment]
Which .NET version are you using?
Also, are you using Visual Studio Code in your project?

**Comment by rrirower** [comment]
Currently targeting .Net 5.  I am using Visual Studio 2022 for coding.  I used Visual Studio Code to create the theme xml file from your contents.

**Comment by Taiizor** [comment]
Can you try to open the following project?

[Taiizor.zip](https://github.com/Taiizor/ReaLTaiizor/files/10290171/Taiizor.zip)

**Comment by rrirower** [comment]
The project opens successfully.  If I try to drag the style manager to the form, I get the above error.

_**Side note**_:  Your ReaLTaiizor.UI.sln solution does allow me to drag a style manager to a form.

**Comment by Taiizor** [comment]
The reason why the ReaLTaiizor.UI project is not giving an error is probably because you are working with the .NET Framework 4.8.
I do not have it installed because .NET 5 has come to an end of support. So I can't test it in .NET 5. But .NET 6 & 7 tests are fine.

**Comment by rrirower** [comment]
OK.  I was going to upgrade my projects to .Net 6.  I'll report back after I upgrade and let you know if it fixed my issue.

**Comment by Taiizor** [comment]
Probably upgrading your project to .NET 6 will not fix the problem, but I will have fixed it in the next release.

**Comment by rrirower** [comment]
Thanks.  I'll look for that release.
